providers = ["node"]
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1736208272'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
[phases.build]
dependsOn = ['install']
cmds = ['npm run build']
cacheDirectories = ['node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = ['npm ci']
cacheDirectories = ['/root/.npm']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = [
    'nodejs_22',
    'npm-9_x',
    'openssl',
]
nixLibs = [
    'gcc-unwrapped',
    'libuuid',
    'libGL',
]
nixOverlays = ['https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz']
nixpkgsArchive = '5624e1334b26ddc18da37e132b6fa8e93b481468'

[start]
cmd = 'npm run start'

